// WordPress webpack config.
const defaultConfig = require('@wordpress/scripts/config/webpack.config');
const webpack = require("webpack");
const {getWebpackEntryPoints} = require("@wordpress/scripts/utils/config")

// Plugins.
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');
const CssMinimizerPlugin = require("css-minimizer-webpack-plugin");
const TerserPlugin = require('terser-webpack-plugin');

// Utilities.
const path = require('path');


// Add any a new entry point by extending the webpack config.
module.exports = [
    {
        ...defaultConfig,
        entry: {
            ...getWebpackEntryPoints(),
        },
    },
    {
        ...defaultConfig,
        ...{
            entry: {
                'js/main': path.resolve(process.cwd(), 'src/js', 'main.js'),
                'css/main': path.resolve(process.cwd(), 'src/scss', 'main.scss'),
                'js/admin': path.resolve(process.cwd(), 'src/js', 'admin.js'),
                'css/admin': path.resolve(process.cwd(), 'src/scss', 'admin.scss'),
            },
            module:
                {
                    ...defaultConfig.module,
                }
            ,
            plugins: [
                // Include WP's plugin config.
                ...defaultConfig.plugins,

                // Removes the empty `.js` files generated by webpack but
                // sets it after WP has generated its `*.asset.php` file.
                new RemoveEmptyScriptsPlugin({
                    stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
                }),
                new webpack.ProvidePlugin({
                    $: "jquery",
                    jQuery: "jquery"
                })
            ],
            optimization: {
                minimize: true,
                minimizer: [
                    // enable the js minification plugin
                    new TerserPlugin({
                        parallel: true
                    }),

                    // enable the css minification plugin
                    new CssMinimizerPlugin(),
                ]
            }
        }
    }
]